baseURL = "https://charly3pins.dev/"
languageCode = "en-us"
title = "charly3pins.dev"
defaultContentLanguage = "en"
pygmentsUseClasses=true
enableRobotsTXT = true
googleAnalytics = "G-KX7XNRQ64E"


[author]
	name = "Charly3Pins"
    email = "hello@charly3pins.dev"

[params]
	author = "Charly3Pins"
	since = 2018
	avatar = "/images/cyberpunk-ai.png"
	errorPage = "/images/gopher-this-is-fine.jpg"
    trendingBlogIcon = "images/trending.svg"
    blogTitle = "Articles"
    blogSubTitle = "View the latest posts"

[languages]
	[languages.en]
		languageName = "English"
		weight = 1
        
        [languages.en.params]
            indexTitle = "Hey! I'm Charly3Pins"
            indexSubTitle = "This is my blog and I post about:"
            indexSubTitleGo = "Learnings in Go"
            indexSubTitleSE = "Experiences working as Software Engineer"
            indexSubTitleProjects = "Projects I code and much more!"
            indexSubTitleEmail = "Want to get in touch?"
    
            [[languages.en.menu.main]]
                name = "Who is ğŸ¤·â€â™‚ï¸"
                url = "whois"
                weight = 1

            [[languages.en.menu.main]]
                name = "Blog âœï¸"
                url = "blog"
                weight = 2
            
            [[languages.en.menu.main]]
                name = "Readings ğŸ“š"
                url = "readings"
                weight = 2

            [[languages.en.menu.main]]
                identifier = "projects"
                name = "Projects ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3
            
            [[languages.en.menu.main]]
                name = "Collectus"
                url = "projects/collectus"
                weight = 1
                parent = "projects"

            [[languages.en.menu.main]]
                name = "Tournaments Generator"
                url = "projects/tournaments-generator"
                weight = 2
                parent = "projects"

            [[languages.en.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4

	[languages.es]
		languageName = "Spanish"
		weight = 2	

        [languages.es.params]
            indexTitle = "Â¡Hola! Soy Charly3Pins"
            indexSubTitle = "Este es mi blog y publicarÃ© sobre:"
            indexSubTitleGo = "Aprendizajes en Go"
            indexSubTitleSE = "Experiencias trabajando como Ingeniero de Software"
            indexSubTitleProjects = "Proyectos que programo y Â¡mucho mÃ¡s!"
            indexSubTitleEmail = "Â¿Quieres ponerte en contacto?"
    
            [[languages.es.menu.main]]
                name = "QuiÃ©n es ğŸ¤·â€â™‚ï¸"
                url = "whois"
                weight = 1

            [[languages.es.menu.main]]
                name = "Blog âœï¸"
                url = "blog"
                weight = 2

            [[languages.es.menu.main]]
                identifier = "projects"
                name = "Proyectos ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3
            
            [[languages.es.menu.main]]
                name = "Collectus"
                url = "projects/collectus"
                weight = 1
                parent = "projects"

            [[languages.es.menu.main]]
                name = "Generador de Torneos"
                url = "projects/tournaments-generator"
                weight = 2
                parent = "projects"

            [[languages.es.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4

	[languages.ca]
		languageName = "Catalan"
		weight = 3

        [languages.ca.params]
            indexTitle = "Hola! Soc Charly3Pins"
            indexSubTitle = "Aquest Ã©s el meu blog i publico sobre:"
            indexSubTitleGo = "Aprenentatge amb Go"
            indexSubTitleSE = "ExperiÃ¨ncies treballant com a Enginyer de Software"
            indexSubTitleProjects = "Projectes que programo i molt mÃ©s!"
            indexSubTitleEmail = "Vols posar-te en contacte?"
    
            [[languages.ca.menu.main]]
                name = "Qui Ã©s ğŸ¤·â€â™‚ï¸"
                url = "whois"
                weight = 1

            [[languages.ca.menu.main]]
                name = "Bloc âœï¸"
                url = "blog"
                weight = 2

            [[languages.ca.menu.main]]
                identifier = "projects"
                name = "Projectes ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3

            [[languages.ca.menu.main]]
                name = "Collectus"
                url = "projects/collectus"
                weight = 1
                parent = "projects"

            [[languages.ca.menu.main]]
                name = "Generador de Tornejos"
                url = "projects/tournaments-generator"
                weight = 2
                parent = "projects"

            [[languages.ca.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4
