baseURL = "https://charly3pins.dev/"
languageCode = "en-us"
title = "charly3pins.dev"

[author]
	name = "Charly3Pins"

[params]
	# Footer CopyRight Info
	## Site creation time
	since = 2018
	avatar = "/images/me.jpeg"
	description = "Software Engineer ğŸ‘¨ğŸ»â€ğŸ’» Gamer ğŸ® and Dog Walker ğŸ•"
	
	# list of sections skipped by RSS
	nofeedSections = ["projects"]
