baseURL = "https://charly3pins.dev/"
languageCode = "en-us"
title = "charly3pins.dev"
googleAnalytics = "UA-126216319-1"
disqusShortname = "charly3pins"

[author]
	name = "Charly3Pins"

[params]
	# Footer CopyRight Info
	## Site creation time
	since = 2018
	avatar = "/images/me.jpeg"
	indexDescription = "Iâ€™m a Software Engineer ğŸ‘¨ğŸ»â€ğŸ’» gamer ğŸ® and dog walker ğŸ•; also, I wrote these articles."
	metaDescription = "Software Engineer ğŸ‘¨ğŸ»â€ğŸ’» gamer ğŸ® and dog walker ğŸ•"
	welcome = "Welcome! Iâ€™m Charly3Pins"

	# list of sections skipped by RSS
	nofeedSections = ["projects"]

[menu]

	[[menu.main]]
		name = "~"
		url = "/"
		weight = -150

	[[menu.main]]
		name = "BLOG"
		url = "/blog/"
		weight = -140
	
	[[menu.main]]
		name = "PROJECTS"
		url = "/projects/"
		weight = -130

	[[menu.main]]
		name = "BOOKS"
		url = "/books/"
		weight = -120
	
	[[menu.main]]
		name = "NOTES"
		url = "/notes/"
		weight = -120

	[[menu.main]]
		name = "$USER"
		url = "/about/"
		weight = -110

	[[menu.main]]
		name = "RSS"
		url = "/index.xml"
		weight = -100