baseURL = "https://charly3pins.dev/"
title = "charly3pins.dev"
metaDataFormat = "yaml"

defaultContentLanguage = "en"

[params.images]
    introPhoto = "/cyberpunk-ai-250px.png"

[languages]
    
    [languages.en]
        weight = 1
        languageName = "English"
    
        [languages.en.params]
            introTitle = "Hey! I'm Charly3Pins"
            introSubtitle = "Eat; Sleep; Code; Repeat;"
    
            [[languages.en.menu.main]]
                name = "About me ğŸ‘‹"
                url = "about"
                weight = 1

            [[languages.en.menu.main]]
                name = "Blog âœï¸"
                url = "blog"
                weight = 2

            [[languages.en.menu.main]]
                name = "Projects ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3

            [[languages.en.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4


    [languages.es]
        weight = 2
        languageName = "EspaÃ±ol"
        title = "charly3pins.dev"
    
        [languages.es.params]
            introTitle = "Â¡Hola! Soy Charly3Pins"
            introSubtitle = "Eat; Sleep; Code; Repeat;"
    
            [[languages.es.menu.main]]
                name = "Acerca de mÃ­ ğŸ‘‹"
                url = "about"
                weight = 1

            [[languages.es.menu.main]]
                name = "Blog âœï¸"
                url = "blog"
                weight = 2

            [[languages.es.menu.main]]
                name = "Proyectos ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3

            [[languages.es.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4

    [languages.ca]
        weight = 1
        languageName = "CatalÃ "
        title = "charly3pins.dev"
    
        [languages.ca.params]
            introTitle = "Hola! Soc Charly3Pins"
            introSubtitle = "Eat; Sleep; Code; Repeat;"
    
            [[languages.ca.menu.main]]
                name = "Sobre mi ğŸ‘‹"
                url = "about"
                weight = 1

            [[languages.ca.menu.main]]
                name = "Bloc âœï¸"
                url = "blog"
                weight = 2

            [[languages.ca.menu.main]]
                name = "Projectes ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3

            [[languages.ca.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4

[author]
	name = "Charly3Pins"

[params]
	since = 2018

    # Enable the darkmode toggle in header
    darkModeToggle = true

    favicon = "/favicon.ico"

    # Color for the intro details and social links block, not applicable for dark mode
    # Supported values: Any color from TailwindCSS default colors
    # Reference: https://tailwindcss.com/docs/customizing-colors
    ascentColor = "bg-blue-100"

    # The page bundle that is shown on the front page
    frontBundle = "blog"

    # Add support for Table of contents
    # Can be added to a page level also in markdown frontmatter
    toc = true

    # Hides the thumbnail in post view
    # Thumbnails in home and blog pages will still be shown
    # This setting can also be in page's markdown file
    hidePageThumbnail = false

# Comments system
[params.comments]
    # Supports disqus, giscus and utterances
    # Check hugo docs for setting up disqus
    system = "giscus"

[params.homepage.social]
    # Global params common for both languages
    title = "Follow me"
    description = "I work on everything coding and tweeting developer memes"

    [[params.homepage.social.icons]]
        website = "twitter"
        url = "https://twitter.com/charly3pins"
    [[params.homepage.social.icons]]
        website = "linkedin"
        url = "https://linkedin.com/in/carlesfuste"
    [[params.homepage.social.icons]]
        website = "github"
        url = "https://github.com/charly3pins"
    [[params.homepage.social.icons]]
        website = "stackoverflow"
        url = "https://stackoverflow.com/users/4948631/charly3pins"
    [[params.homepage.social.icons]]
        website = "dev.to"
        url = "https://dev.to/charly3pins"
    [[params.homepage.social.icons]]
        website = "rss"
        url = "https://charly3pins.dev/index.xml"

[build]
    writeStats = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
    [markup.highlight]
        style = "dracula"
    [markup.goldmark.renderer]
        # Enable to include inline HTML
        unsafe = true