baseURL = "https://charly3pins.dev/"
title = "Charly3Pins.dev"
languageCode = "es-es"
paginate = "10" # Number of posts per page
googleAnalytics = "G-KX7XNRQ64E"

# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "software engineering, programador, engineering, programar, golang, charly3pins"
  headerTitle = "Charly3Pins"
  copyright = "¬© 2018 - 2024 Charly3Pins. All rights reserved."
  name = "charly3pins"
  #img = "images/cyberpunk-ai.png"
  img = "images/me-retro.jpeg"
  img_title = ""
  icon = "images/face.ico"
  quote = "üåö <span style=\"font-style:italic;\">Entre el 0 y el 1</span> üåù"
  description= """¬°Hola y bienvenido a mi espacio digital!
<br><br>
Soy Carles, pero se me conoce como Charly3Pins. Durante m√°s de una d√©cada, he estado inmerso en el apasionante mundo de la ingenier√≠a de software. Aqu√≠ compartir√© contigo mis vivencias, reflexiones y conocimientos acumulados a lo largo de este viaje tecnol√≥gico.
<br><br>
Imagina este lugar como un oasis donde convergen mis experiencias, ideas y pasiones. Desde art√≠culos sobre temas que me cautivan hasta tutoriales que te guiar√°n en el fascinante arte de la programaci√≥n. No faltar√°n proyectos en los que dedico mi tiempo y energ√≠a, siempre buscando traspasar los l√≠mites de lo posible.
<br><br>
Con un bagaje diverso y una curiosidad insaciable, abrazo cada desaf√≠o con entusiasmo. Mi misi√≥n es crear soluciones que no solo cumplan con los est√°ndares, sino que los superen, manteniendo siempre la seguridad, resiliencia y escalabilidad como pilares fundamentales.
<br><br>
Me considero un eterno aprendiz, siempre sediento de conocimiento y √°vido de explorar nuevas tecnolog√≠as. Desde que descubr√≠ <a href="https://go.dev/">Go</a>, experiment√© un flechazo instant√°neo. Este lenguaje encarna el <a href="https://en.wikipedia.org/wiki/KISS_principle">principio KISS</a> que tanto valoro, y me emociona formar parte de su crecimiento y evoluci√≥n.
<br><br>
Pero aqu√≠ no termina la historia. Adem√°s de seguirme en mis redes sociales como <a href="https://twitter.com/charly3pins">@charly3pins</a> y explorar mis proyectos en <a href="https://github.com/charly3pins">GitHub</a>, te invito a sumergirte en este universo tecnol√≥gico junto a m√≠. ¬øEst√°s listo para embarcarte en esta emocionante traves√≠a?
<br><br>
¬°√önete a m√≠ y descubre el fascinante mundo de la tecnolog√≠a a trav√©s de mis ojos!"""

  licenseUrl = ""

 # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/charly3pins"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/charly3pins"

  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/charly3pins"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/carlesfuste"

  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/charly3pins"

  [[params.social]]
    name = "email"
    url  = "mailto:hello@charly3pins.dev"

[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Inicio"
    url        = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog/"

  [[menu.main]]
    identifier = "projects"
    name       = "Proyectos"
    url        = "/projects/"

  [[menu.main]]
    identifier = "biblioteca"
    name       = "Biblioteca"
    url        = "/biblioteca/"
