baseURL = "https://charly3pins.dev/"
languageCode = "en-us"
title = "charly3pins.dev"
googleAnalytics = "UA-126216319-1"
disqusShortname = "https-charly3pins-dev"
defaultContentLanguage = "en"
pygmentsUseClasses=true
enableRobotsTXT = true

[author]
	name = "Charly3Pins"

[params]
	since = 2018
	# avatar = "/images/law-mustache.gif"
	avatar = "/images/cyberpunk-ai.png"
	errorPage = "/images/gopher-this-is-fine.jpg"

[languages]
	[languages.en]
		languageName = "English"
		weight = 1
        
        [languages.en.params]
            introTitle = "Hey! I'm Charly3Pins"
            introSubtitle = "Eat; Sleep; Code; Repeat;"
    
            [[languages.en.menu.main]]
                name = "About me ğŸ‘‹"
                url = "about"
                weight = 1

            [[languages.en.menu.main]]
                name = "Blog âœï¸"
                url = "blog"
                weight = 2

            [[languages.en.menu.main]]
                name = "Projects ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3

            [[languages.en.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4

	[languages.es]
		languageName = "Spanish"
		weight = 2	

        [languages.es.params]
            introTitle = "Â¡Hola! Soy Charly3Pins"
            introSubtitle = "Eat; Sleep; Code; Repeat;"
    
            [[languages.es.menu.main]]
                name = "Acerca de mÃ­ ğŸ‘‹"
                url = "about"
                weight = 1

            [[languages.es.menu.main]]
                name = "Blog âœï¸"
                url = "blog"
                weight = 2

            [[languages.es.menu.main]]
                name = "Proyectos ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3

            [[languages.es.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4

	[languages.ca]
		languageName = "Catalan"
		weight = 3

        [languages.ca.params]
            introTitle = "Hola! Soc Charly3Pins"
            introSubtitle = "Eat; Sleep; Code; Repeat;"
    
            [[languages.ca.menu.main]]
                name = "Sobre mi ğŸ‘‹"
                url = "about"
                weight = 1

            [[languages.ca.menu.main]]
                name = "Bloc âœï¸"
                url = "blog"
                weight = 2

            [[languages.ca.menu.main]]
                name = "Projectes ğŸ‘¨â€ğŸ’»"
                url = "projects"
                weight = 3

            [[languages.ca.menu.main]]
                name = "Tags ğŸ” "
                url = "tags"
                weight = 4